# Problem 1 

In [2]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 5 elemanlı bir numpy array oluşturun
arr = np.array([7, 2, 4, 1, 9])

# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
sorted_arr = np.sort(arr)

print("Oluşturulan Array:", arr)
print("Sıralanmış Array:", sorted_arr)


Oluşturulan Array: [7 2 4 1 9]
Sıralanmış Array: [1 2 4 7 9]


# Problem 2

In [13]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
import numpy as np

arr1 = np.array([10, 15, 30, 45, 60])
print(arr1)



# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
arr2 = np.arange(5, 16)
print(arr2)

 
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
arr3 = np.arange(50, 101, 5)
print(arr3)



# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
arr4 = np.zeros(10)
print(arr4)



# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
arr5 = np.ones(10)
print(arr5)



# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
arr6 = np.linspace(0, 100, 5)
print(arr6)



# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
arr7 = np.random.randint(10, 30, 5)
print(arr7)



# 8- [-1 ile 1] arasında 10 adet sayı üretin.
arr8 = np.random.uniform(-1, 1, 10)
print(arr8)




# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
matris = np.random.randint(10, 51, size=(3, 5))
print(matris)



# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?

row_sum = np.sum(matris, axis=1)
column_sum = np.sum(matris, axis=0)

print("Satır toplamları:", row_sum)
print("Sütun toplamları:", column_sum)


# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?

max_value = np.max(matris)
min_value = np.min(matris)
mean_value = np.mean(matris)

print("En büyük değer:", max_value)
print("En küçük değer:", min_value)
print("Ortalama değer:", mean_value)


# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?

max_index = np.argmax(matris)
print("En büyük değerin indeksi:", max_index)


# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.

arr = np.arange(10, 21)
ilk_üç_eleman = arr[:3]

print("İlk üç eleman:", ilk_üç_eleman)


# 14- Üretilen dizinin elemanlarını tersten yazdırın.

Tersten = np.flip(arr)

print("Dizinin ters hali:", Tersten)


# 15- Üretilen matrisin ilk satırını seçiniz.

ilk_satır = matris[0]

print("İlk satır:", ilk_satır)


# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?

eleman = matris[1, 2]

print("2. satır 3. sütundaki eleman:", eleman)


# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.

ilk_eleman = matris[:, 0]

print("Tüm satırlardaki ilk elemanlar:", ilk_eleman)


# 18- Üretilen matrisin her bir elemanının karesini alınız.
Karesi = np.square(matris)

print("Her bir elemanın karesi:", Karesi)

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.

pozitive_çift_sayılar = matris[(matris % 2 == 0) & (matris > 0)]

print("Pozitif çift sayılar:", pozitive_çift_sayılar)


[10 15 30 45 60]
[ 5  6  7  8  9 10 11 12 13 14 15]
[ 50  55  60  65  70  75  80  85  90  95 100]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[27 28 25 20 11]
[ 0.45798526  0.10098025  0.06181285 -0.17950358  0.86076758 -0.89687941
 -0.56003867 -0.16770466 -0.74893473 -0.6445089 ]
[[23 41 12 29 48]
 [35 36 33 19 25]
 [21 46 39 15 45]]
Satır toplamları: [153 148 166]
Sütun toplamları: [ 79 123  84  63 118]
En büyük değer: 48
En küçük değer: 12
Ortalama değer: 31.133333333333333
En büyük değerin indeksi: 4
İlk üç eleman: [10 11 12]
Dizinin ters hali: [20 19 18 17 16 15 14 13 12 11 10]
İlk satır: [23 41 12 29 48]
2. satır 3. sütundaki eleman: 33
Tüm satırlardaki ilk elemanlar: [23 35 21]
Her bir elemanın karesi: [[ 529 1681  144  841 2304]
 [1225 1296 1089  361  625]
 [ 441 2116 1521  225 2025]]
Pozitif çift sayılar: [12 48 36 46]
