# Problem 1

In [1]:
# 1 - numpy kütüphanesini import edin

import numpy as np

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin

matris = np.random.randint(0, 11, (5,))
print("Matris:\n", matris)


# 3 - matris'in boyutunu öğrenin

boyut = matris.shape
print("Matris Boyutu:", boyut)


# 4 - matris'i yeniden boyutlandırın

yeniden_boyutlu_matris = matris.reshape((1, 5))
print("Yeniden Boyutlandırılmış Matris:\n", yeniden_boyutlu_matris)


# 5 - matris'in boyut sayısını öğrenin

boyut_sayisi = matris.ndim
print("Matris Boyut Sayısı:", boyut_sayisi)

Matris:
 [ 6  2  7  8 10]
Matris Boyutu: (5,)
Yeniden Boyutlandırılmış Matris:
 [[ 6  2  7  8 10]]
Matris Boyut Sayısı: 1


# Problem 2

In [8]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
import numpy as np

matris = np.arange(1, 10, 2)
print("Matris:\n", matris)


# 2 - Oluşturduğunuz matrisi parçalayın

parcalanmis_matris = np.split(matris, 5)
print("Parçalanmış Matrisler:")
for parca in parcalanmis_matris:
    print(parca)



# 3 - Parçalanmış matrisleri birleştirin

birlesik_matris = np.concatenate(parcalanmis_matris)
print("Birleştirilmiş Matris:\n", birlesik_matris)

Matris:
 [1 3 5 7 9]
Parçalanmış Matrisler:
[1]
[3]
[5]
[7]
[9]
Birleştirilmiş Matris:
 [1 3 5 7 9]


# Problem 3

In [5]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
import numpy as np

matris = np.random.choice(np.arange(5, 101, 2), size=(10,))
print("Matris:\n", matris)

# 2 - matris'in özelliklerini inceleyin
print("Matris Özellikleri:")
print("Boyut:", matris.shape)
print("Eleman Sayısı:", matris.size)
print("Boyut Sayısı:", matris.ndim)
print("Veri Tipi:", matris.dtype)
print("Minimum Değer:", np.min(matris))
print("Maksimum Değer:", np.max(matris))
print("Toplam:", np.sum(matris))
print("Ortalama:", np.mean(matris))
print("Standart Sapma:", np.std(matris))



Matris:
 [57 21 11 11 15 27 49 19 61 15]
Matris Özellikleri:
Boyut: (10,)
Eleman Sayısı: 10
Boyut Sayısı: 1
Veri Tipi: int32
Minimum Değer: 11
Maksimum Değer: 61
Toplam: 286
Ortalama: 28.6
Standart Sapma: 18.478095139921756
